import type { Metadata } from "next";
import { Footer, Layout, Navbar } from 'nextra-theme-docs'
import { Banner, Head } from 'nextra/components'
import { getPageMap } from 'nextra/page-map'
import 'nextra-theme-docs/style.css'
import 'katex/dist/katex.min.css'


export const metadata: Metadata = {
    title: " docs",
    description: "Generated by create next app",
};
const navbar = (
    <Navbar
        logo={<b>LDocs</b>}
    // ... Your additional navbar options
    />
)

const footer = <Footer>MIT {new Date().getFullYear()} © Nextra.</Footer>
export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html             // Not required, but good for SEO
            lang="en"
            dir="ltr"
            // Suggested by `next-themes` package https://github.com/pacocoursey/next-themes#with-app
            suppressHydrationWarning>
            <Head
            // ... Your additional head options
            >
                {/* Your additional tags should be passed as `children` of `<Head>` element */}
            </Head>
            <body>
                <Layout
                    // banner={banner}
                    navbar={navbar}
                    pageMap={await getPageMap()}
                    editLink={null}
                    feedback={{content:null}}
                // docsRepositoryBase="https://github.com/shuding/nextra/tree/main/docs"
                // footer={footer}
                // ... Your additional layout options
                >
                    {children}
                </Layout>      
            </body>
        </html>
    );
}